backend:
  name: git-gateway
  branch: main # Replace with your branch name
media_folder: "static/images/uploads" # Where images are stored
public_folder: "/images/uploads"
collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "number" }
